import Foundation

public enum L10n {
    public static let timerTitle = tr("timer.title", "Timer screen title")
    public static let timerSubtitle = tr("timer.subtitle", "Timer informational subtitle")
    public static let stateLabel = tr("timer.state.label", "State label")
    public static let milestoneLabel = tr("timer.milestone.label", "Milestone label")
    public static let elapsedLabel = tr("timer.elapsed.label", "Elapsed label")
    public static let elapsedFormat = tr("timer.elapsed.format", "Elapsed time format")
    public static let primaryStart = tr("timer.primary.start", "Start action")
    public static let primaryStop = tr("timer.primary.stop", "Stop action")
    public static let abandon = tr("timer.abandon", "Abandon action")
    public static let statusIdle = tr("timer.status.idle", "Idle state")
    public static let statusActive = tr("timer.status.active", "Active state")
    public static let statusCompleted = tr("timer.status.completed", "Completed state")
    public static let statusAbandoned = tr("timer.status.abandoned", "Abandoned state")
    public static let milestoneNone = tr("timer.milestone.none", "No milestone text")
    public static let milestoneDigestiveCompletion = tr("timer.milestone.digestiveCompletion", "Digestive completion milestone")
    public static let milestoneEarlyMetabolicShift = tr("timer.milestone.earlyMetabolicShift", "Early metabolic shift milestone")
    public static let milestoneIncreasingMetabolicFlexibility = tr("timer.milestone.increasingMetabolicFlexibility", "Increasing metabolic flexibility milestone")
    public static let milestoneDeeperFastingState = tr("timer.milestone.deeperFastingState", "Deeper fasting state milestone")
    public static let milestoneExtendedFasting = tr("timer.milestone.extendedFasting", "Extended fasting milestone")

    public static let forestTitle = tr("forest.title", "Forest title")
    public static let forestSubtitle = tr("forest.subtitle", "Forest subtitle")
    public static let lockedTreeAccessibility = tr("forest.tree.locked", "Locked tree a11y label")
    public static let unlockedTreeAccessibility = tr("forest.tree.unlocked", "Unlocked tree a11y label")
    public static let treeHint = tr("forest.tree.hint", "Tree accessibility hint")

    public static let calendarTitle = tr("calendar.title", "Calendar title")
    public static let calendarEntries = tr("calendar.entries", "Calendar entries section title")
    public static let calendarLocked = tr("calendar.locked", "Calendar locked section title")
    public static let calendarInspectable = tr("calendar.inspectable", "Inspectable label")
    public static let calendarLockedLabel = tr("calendar.locked.label", "Locked label")

    public static let settingsTitle = tr("settings.title", "Settings title")
    public static let settingsSectionSubscriptions = tr("settings.section.subscriptions", "Subscriptions section")
    public static let settingsSectionData = tr("settings.section.data", "Data portability section")
    public static let exportData = tr("settings.export", "Export data action")
    public static let importData = tr("settings.import", "Import data action")
    public static let importRequiresConfirmation = tr("settings.import.confirmation", "Import confirmation note")
    public static let importSuccess = tr("settings.import.success", "Import success message")
    public static let manageSubscriptions = tr("settings.manage.subscriptions", "Manage subscriptions link")
    public static let localDataExplanation = tr("settings.data.explanation", "Local data deletion warning")

    public static let paywallTitle = tr("paywall.title", "Paywall title")
    public static let paywallSubtitle = tr("paywall.subtitle", "Paywall subtitle")
    public static let paywallAnnual = tr("paywall.annual", "Annual product label")
    public static let paywallLifetime = tr("paywall.lifetime", "Lifetime product label")
    public static let paywallRestore = tr("paywall.restore", "Restore purchases action")
    public static let paywallPrivacy = tr("paywall.privacy", "Privacy reassurance")
    public static let paywallLocalOnly = tr("paywall.local", "Local-only reassurance")
    public static let paywallRenewal = tr("paywall.renewal", "Renewal disclosure")
    public static let paywallTerms = tr("paywall.terms", "Terms of Service label")
    public static let paywallPrivacyLink = tr("paywall.privacy.link", "Privacy Policy label")
    public static let paywallTermsURL = tr("paywall.terms.url", "Terms URL")
    public static let paywallPrivacyURL = tr("paywall.privacy.url", "Privacy URL")
    public static let paywallSelect = tr("paywall.select", "Select product action")
    public static let paywallStatusIdle = tr("paywall.status.idle", "Idle status")
    public static let paywallStatusPurchasing = tr("paywall.status.purchasing", "Purchasing status")
    public static let paywallStatusRestoring = tr("paywall.status.restoring", "Restoring status")
    public static let paywallStatusError = tr("paywall.status.error", "Error status prefix")
    public static let paywallStatusSuccess = tr("paywall.status.success", "Success status")
    public static let paywallTrialNotice = tr("paywall.trial.notice", "Trial notice at fast 11")

    public static let tabTimer = tr("tab.timer", "Tab timer")
    public static let tabForest = tr("tab.forest", "Tab forest")
    public static let tabCalendar = tr("tab.calendar", "Tab calendar")
    public static let tabWater = tr("tab.water", "Tab water")
    public static let tabSettings = tr("tab.settings", "Tab settings")

    public static let waterTitle = tr("water.title", "Water screen title")
    public static let waterSubtitle = tr("water.subtitle", "Water screen subtitle")
    public static let waterToday = tr("water.today", "Water today label")
    public static let waterAdd250 = tr("water.add250", "Water add 250ml action")

    private static func tr(_ key: String, _ comment: String) -> String {
        NSLocalizedString(key, bundle: .module, comment: comment)
    }
}
